# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
    "mmc_block"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "cryptd"
  ];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.initrd.luks.devices.cryptroot.device = "/dev/disk/by-uuid/714d8d85-3444-4a28-937c-ab967e2737e8";
  fileSystems."/" = {
    device = "/dev/mapper/lvmroot-root";
    fsType = "ext4";
  };

  fileSystems."/media/sdcard" = {
    device = "/dev/disk/by-uuid/70553896-3b13-4964-ba55-582b001fc7ab";
    fsType = "ext4";
    options = [
      "nofail"
      "x-systemd.automount"
      "x-systemd.idle-timeout=60"
    ];
  };
  # auto unlock luks with /luks.key from the sd card, falls back to password if missing
  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices.cryptroot = {
    keyFile = "/bin:UUID=70553896-3b13-4964-ba55-582b001fc7ab";
    crypttabExtraOpts = ["keyfile-timeout=5s"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9BF3-A979";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
