# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/98db8721-e4cd-46f0-88a7-2e0c9db933f9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C5FD-5B9C";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };
  # fileSystems."/mnt/media" = {
  #   device = "/dev/disk/by-uuid/  3adbc2de-9e0f-4c22-869d-52aed90e91f9";
  #   fsType = "ext4";
  #   options = [
  #     "defaults"
  #     "nofail"
  #   ];
  # };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
